Repository BetonQuest/BetonQuest, pull requests merged in 2020-07, with the labels that each got.

#1145 experimental movenpc event fix
  CHANGELOG.md
  src/main/java/pl/betoncraft/betonquest/compatibility/citizens/NPCMoveEvent.java
Labels: Further Information Required

#1172 Docs: Configuration,Updating,Backups Rework
  CHANGELOG.md
  docs/Learn-Beton/Installation-and-Configuration.md
  docs/User-Documentation/Configuration.md
  docs/User-Documentation/Conversations.md
  docs/User-Documentation/Reference.md
  docs/User-Documentation/Updating-and-Backups.md
  mkdocs.yml
  src/main/java/pl/betoncraft/betonquest/events/TeleportEvent.java
Labels: User Docs (Wiki)

#1184 Clean up maven dependencies
  pom.xml
Labels: Bug, Confirmed
